In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
import pickle as pkl

In [2]:
df = pd.read_csv(r"C:\Hassan\AI Projects and learning 2026\Projects\Loan Approval\data\loan_data.csv")

In [3]:
df = df.drop(columns=["person_age","person_emp_exp","loan_amnt","person_gender","person_education","cb_person_cred_hist_length","credit_score"])
# Combine EDUCATION, PERSONAL, MEDICAL into EPM
df['loan_intent'] = df['loan_intent'].map({
    'EDUCATION': 'EPM',
    'PERSONAL': 'EPM', 
    'MEDICAL': 'EPM',
    'nan': 'EPM',
    'VENTURE': 'VENTURE',    # keep as is
    'HOMEIMPROVEMENT': 'HOMEIMPROVEMENT'  # keep as is
})
df["loan_intent"] = df['loan_intent'].fillna("EPM")
df['loan_intent'].unique()

<StringArray>
['EPM', 'VENTURE', 'HOMEIMPROVEMENT']
Length: 3, dtype: str

In [4]:
df.head(1)

,person_income,person_home_ownership,loan_intent,loan_int_rate,loan_percent_income,previous_loan_defaults_on_file,loan_status
0,71948.0,RENT,EPM,16.02,0.49,No,1

In [5]:

# Encode
categorical_cols = ["person_home_ownership","loan_intent","previous_loan_defaults_on_file"]
encoder = OneHotEncoder(sparse_output=False)

    
data_encoded = encoder.fit_transform(df[categorical_cols])
df = df.drop(categorical_cols, axis=1)
df = pd.concat([df, pd.DataFrame(data_encoded, columns=encoder.get_feature_names_out(), index=df.index)], axis=1)

In [6]:
df.head()

,person_income,loan_int_rate,loan_percent_income,loan_status,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EPM,loan_intent_HOMEIMPROVEMENT,loan_intent_VENTURE,previous_loan_defaults_on_file_No,previous_loan_defaults_on_file_Yes
0,71948.0,16.02,0.49,1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
1,12282.0,11.14,0.08,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,12438.0,12.87,0.44,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,79753.0,15.23,0.44,1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
4,66135.0,14.27,0.53,1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0

In [7]:
X = df.drop(columns ="loan_status")
y = df["loan_status"]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [9]:
from xgboost import XGBClassifier
from sklearn.ensemble import HistGradientBoostingClassifier

In [10]:
from sklearn.metrics import classification_report, confusion_matrix

In [11]:
xgb_model = XGBClassifier()

In [12]:
hgb_model = HistGradientBoostingClassifier()

In [13]:
scaler = MinMaxScaler()

In [14]:
scaler.fit(X_train)
X_train_scaled = pd.DataFrame(scaler.transform(X_train), columns=X_train.columns)
X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)

In [15]:
xgb_model.fit(X_train_scaled,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [16]:
hgb_model.fit(X_train_scaled, y_train)

HistGradientBoostingClassifier()

In [17]:
y_xgb = xgb_model.predict(X_test_scaled)
y_hgb = hgb_model.predict(X_test_scaled)

In [18]:
print("XGB MODEL:")
print(classification_report(y_test, y_xgb))
print("Hist Gradient MODEL:")
print(classification_report(y_test, y_hgb))

XGB MODEL:
              precision    recall  f1-score   support

           0       0.95      0.97      0.96      3593
           1       0.87      0.79      0.83       907

    accuracy                           0.93      4500
   macro avg       0.91      0.88      0.89      4500
weighted avg       0.93      0.93      0.93      4500

Hist Gradient MODEL:
              precision    recall  f1-score   support

           0       0.94      0.97      0.96      3593
           1       0.88      0.77      0.82       907

    accuracy                           0.93      4500
   macro avg       0.91      0.87      0.89      4500
weighted avg       0.93      0.93      0.93      4500

In [19]:
importances = xgb_model.feature_importances_
feat_names = X_train_scaled.columns

# Create a DataFrame for easy sorting and plotting
df_importance = pd.DataFrame({'Feature': feat_names, 'Importance': importances})
df_importance = df_importance.sort_values(by='Importance', ascending=True)

In [20]:
df_importance

                               Feature  Importance
11  previous_loan_defaults_on_file_Yes    0.000000
3       person_home_ownership_MORTGAGE    0.002008
4          person_home_ownership_OTHER    0.002855
7                      loan_intent_EPM    0.003717
0                        person_income    0.006859
1                        loan_int_rate    0.009030
8          loan_intent_HOMEIMPROVEMENT    0.009444
9                  loan_intent_VENTURE    0.010223
2                  loan_percent_income    0.012401
5            person_home_ownership_OWN    0.016960
6           person_home_ownership_RENT    0.022531
10   previous_loan_defaults_on_file_No    0.903972

In [30]:
useless_features = []

for i in range(df_importance.shape[0]):  # [0] = rows
    if df_importance.iloc[i]['Importance'] < 0.005:
        useless_features.append(df_importance.iloc[i]['Feature'])

print(f"Useless features ({len(useless_features)}):")
print(useless_features)

Useless features (4):
['previous_loan_defaults_on_file_Yes', 'person_home_ownership_MORTGAGE', 'person_home_ownership_OTHER', 'loan_intent_EPM']

In [22]:
print(confusion_matrix(y_test, y_xgb))
print(confusion_matrix(y_test, y_hgb))

[[3490  103]
 [ 191  716]]
[[3495   98]
 [ 212  695]]

In [31]:
X_train_scaled.drop(columns=useless_features).head()
X_test_scaled.drop(columns=useless_features).head()

,person_income,loan_int_rate,loan_percent_income,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_HOMEIMPROVEMENT,loan_intent_VENTURE,previous_loan_defaults_on_file_No
0,0.010553,0.462277,0.196970,0.0,1.0,0.0,0.0,1.0
1,0.009195,0.416324,0.348485,0.0,1.0,0.0,0.0,0.0
2,0.004232,0.553498,0.121212,0.0,1.0,0.0,0.0,0.0
3,0.010575,0.628944,0.454545,0.0,1.0,1.0,0.0,1.0
4,0.014837,0.759259,0.075758,0.0,1.0,0.0,0.0,1.0

In [33]:
pkl.dump(xgb_model, open(r'C:\Hassan\AI Projects and learning 2026\Projects\Loan Approval\model.pkl', 'wb'))
pkl.dump(scaler, open(r'C:\Hassan\AI Projects and learning 2026\Projects\Loan Approval\scaler.pkl', 'wb'))
pkl.dump(encoder, open(r'C:\Hassan\AI Projects and learning 2026\Projects\Loan Approval\encoder.pkl', 'wb'))